"""empty message

Revision ID: bd13772976b1
Revises: 62aebfc3ab16
Create Date: 2023-03-01 15:24:23.792702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd13772976b1'
down_revision = '62aebfc3ab16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reward_points')

    op.create_table('points',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reward_points', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
